version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - db-data-dev:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  db_test:
    image: mysql:5.7
    volumes:
      - db-data-test:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress_test
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: docker-press-develop:latest
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    volumes:
      - ./wordpress-develop:/var/www/html
    ports:
      - 8088:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db
      - db_test

volumes:
  db-data-dev:
  db-data-test:
